name: Update Counter

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER_NAME: ${{ github.repository_owner }}
      GITHUB_USER_EMAIL: "YourEmail@example.com"
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ env.GITHUB_USER_NAME }}"
          git config user.email "${{ env.GITHUB_USER_EMAIL }}"

      - name: Increment counter
        run: |
          echo $(( $(cat counter.txt) + 1 )) > counter.txt

      - name: Commit and push changes
        run: |
          git add counter.txt
          git commit -m "Incremented counter to $(cat counter.txt)"
          git push https://$PAT_TOKEN@github.com/${{ github.repository }}.git ${{ github.ref }}