name: Update Counter

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch GitHub user details
        id: fetch-details
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.users.getByUsername({
              username: process.env.REPO_OWNER
            });
            core.setOutput("name", response.data.name);
            core.setOutput("email", response.data.email || "YourEmail@example.com"); // Fallback if email is not public

      - name: Set up Git
        run: |
          git config user.name "${{ steps.fetch-details.outputs.name }}"
          git config user.email "${{ steps.fetch-details.outputs.email }}"

      - name: Increment counter
        run: |
          echo $(( $(cat counter.txt) + 1 )) > counter.txt

      - name: Commit and push changes
        run: |
          git add counter.txt
          git commit -m "Incremented counter to $(cat counter.txt)"
          git push https://$PAT_TOKEN@github.com/${{ github.repository }}.git ${{ github.ref }}